// <auto-generated />
namespace SmartSnag.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201705162118415_AddChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
